### PR TITLE
Make app deployable.

### PR DESCRIPTION
**Pull request by cowboy**
Is there anything else I'm missing?

### CODE REVIEW

**Comment by cowboy** [comment]
@tkellen anything else you can think of that's critical to deploying this app?

**Comment by tkellen** [comment]
Yes, you're missing DB_USER and DB_NAME for the actual service.

**Comment by tkellen** [comment]
We should probably also put skillsbot.bocoup.com behind a user/pass until we're ready to share it with the world. I'll share an example of an existing repo where we do this in slack.

**Comment by cowboy** [comment]
> Yes, you're missing DB_USER and DB_NAME for the actual service.

Fixed!

**Comment by cowboy** [comment]
> We should probably also put skillsbot.bocoup.com behind a user/pass until we're ready to share it with the world. I'll share an example of an existing repo where we do this in slack.

Will the "add app to my slack" flow work for Bocoup if there's a password?

**Comment by tkellen** [comment]
Yes. We could also just turn off the nginx service.

**Comment by cowboy** [comment]
> Yes. We could also just turn off the nginx service.

I'd rather not rely on deploying different commits to enable and disable functionality. I'd prefer that the app just works as we need it to without any extra fiddling around.

**Comment by tkellen** [comment]
In that case, I think it makes sense to add password protection until we're ready for teams other than our own to use this.

**Comment by cowboy** [comment]
> In that case, I think it makes sense to add password protection until we're ready for teams other than our own to use this.

Ok, I added a commit for this, but I'm not totally sure it makes sense. Can you review?

**Pull request merged**
