### PR TITLE
Add support for testing deployment in vagrant. Closes #60.

### LINKED ISSUE #60: Add vagrant config/playbooks for testing deployment
See https://github.com/bocoup/bots/pull/161/commits

### PR DESCRIPTION
**Pull request by cowboy**
1. `vagrant up`
2. `ssh skillsbot.loc`
3. `sudo vim /etc/init/slack_bot.conf`
   - change tokens and/or databases to dev values for testing
4. `exit` (from vagrant)
5. `./deploy/run-playbook.sh deploy vagrant local=true`

### CODE REVIEW

**Comment by cowboy** [comment]
@tkellen can you review? once this is good to go, i'll merge and do the same thing to pombot.

**Comment by tkellen** [comment]
trying now

**Comment by tkellen** [comment]
Looking good! Just as a heads up, I shut down the production skills bot manually (since it isn't currently in use) and confirmed by bringing it up locally.

**Comment by cowboy** [comment]
Ok. @iamjessklein was using the "production" skillsbot to do some testing earlier today, but she may have finished already.

**Pull request merged**
