### PR TITLE
Rename "expertisebot" to "skillsbot". Closes #27.

### LINKED ISSUE #27: rename to skillsbot
- [ ] rename everything inside the bot
- [ ] rename the repo

### PR DESCRIPTION
**Pull request by cowboy**
Lots of changes, please test!

It's currently running in our Slack as @skillsbot, so you can test there. Bonus points if you want to spin up your own per the instructions at https://github.com/bocoup/skillsbot/wiki/Development (although the fetching secrets and "creating a database" parts probably won't work yet.

/cc @tkellen @jennschiffer

### CODE REVIEW

**Comment by tkellen** [comment]
While speaking to skillsbot in Slack:

```
[4:10 PM]  tkellen find c++
[4:10 PM]  Expertise Test Bot BOT An error occurred: `relation "expertise" does not exist
```

**Comment by cowboy** [comment]
@tkellen please try again, I might have accidentally switched back into `master`.

**Comment by cowboy** [comment]
@tkellen I have update the Development wiki page to better reflect the process for creating (and removing) a temporary database: https://github.com/bocoup/skillsbot/wiki/Development

**Comment by tkellen** [comment]
The wiki notes need to include that you should be connected to our VPN to do this stuff (or in one of our facilities).

**Comment by tkellen** [comment]
Also that you have postgresql installed locally so you can run the commands. For OSX that's http://postgresapp.com/ or `brew install postgresql`

**Comment by jennschiffer** [comment]
i'm getting Error: `No data returned from the query.` when i try `bocoup-import`

**Comment by jennschiffer** [comment]
but i do have the bocoup db stuff in .env

**Comment by cowboy** [comment]
@tkellen I've updated the wiki to mention the VPN and the dev dependencies.

> i'm getting Error: No data returned from the query. when i try bocoup-import

@jennschiffer you can't do the import unless you're connected to Bocoup's slack!

**Comment by jennschiffer** [comment]
👍  works for me in our slack

**Pull request merged**
